language: node_js
branches:
  only:
  - master
node_js:
  - '10'
cache: yarn
install:
  - npm install -g firebase-tools
  - yarn install
script:
  - yarn run build --mode=production
after_success:
  - firebase deploy
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT