language: node_js
branches:
  only:
  - master
node_js:
  - '8'
cache: yarn
install:
  - npm install -g firebase-tools
  - yarn install
  - yarn run build --mode=development
after_success:
  - yarn run deploy -- --token $FIREBASE_TOKEN

