language: node_js
branches:
  only:
  - master
node_js:
  - '8'
cache: yarn
before_install:
  - npm install -g firebase-tools
install:
  - yarn install
script:
  - yarn run build --mode=production
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
