language: node_js
branches:
  only:
  - feature-fix-travis
node_js:
  - '8'
cache: yarn
install:
  - yarn install
script:
  - yarn run build --mode=development
 after_success:
  - yarn run deploy -- --token $FIREBASE_TOKEN


